server:
  port: 8080

spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
      show-sql: true
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
    initialization-mode: never # Para inserir dados utilize o valor {always} ou {never} para não inserir