CREATE TABLE IF NOT EXISTS post (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username character varying(255) NOT NULL,
    content text NOT NULL,
    upvotes integer NOT NULL,
    user_id bigint NOT NULL
);
